version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rental  # This should match your Django database name
      POSTGRES_USER: postgres  # This should match your Django database user
      POSTGRES_PASSWORD: 456977  # This should match your Django database password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: rental
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 456977
      DATABASE_HOST: db
      DATABASE_PORT: 5432

volumes:
  postgres_data: